services:
  ultralytics:
    build: .
    container_name: ultralytics-docker
    runtime: nvidia
    volumes:
      - .:/app
      - ./datasets:/datasets
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ipc: host
    command: tail -f /dev/null